name: project_translator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 라우터
  http: ^1.1.0
  # 음성관련
  flutter_tts: ^3.8.3
  speech_to_text: ^6.3.0
  # 음성번역에 마이크 버튼 효과
  avatar_glow: ^2.0.2
  # 카메라 & 이미지 자르기
  camera: ^0.10.5+5
  image_cropper: ^5.0.0
  # 갤러리
  image_picker: ^1.0.4
  # text ocr
  google_mlkit_text_recognition: ^0.10.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700